add pagesize setting to the backend
latex3/latex3 pull request #1100
Opened 2022-06-21 10:44 UTC by u-fischer

This adds the code to set the mediabox /pagesize currently used in graphics-def into l3backend so that the  mediabox are set always and not only if packages like graphics or geometry are loaded. 

There is no public interface currently (changing the pagesize in mid-document doesn't work for all engines with these functions) and testfiles are still missing.

2022-06-21 20:33 UTC, josephwright requested changes
We have a lot of common code here, which doesn't live in `l3backend` at all. We need to work out where this is going at a different level - for the present could be `l3pdf` I think.

2022-06-21 20:33 UTC, josephwright commented on l3backend/l3backend-pdf.dtx
> +         \cs_if_exist:NTF \stockwidth
Do we really need this?

2022-06-21 20:33 UTC, josephwright commented on l3backend/l3backend-pdf.dtx
> +\tl_gput_right:Nn \@kernel@before@begindocument
We can't be sure that this exists: remember that the backend has to work with non-LaTeX format.s

2022-06-21 20:33 UTC, josephwright commented on l3backend/l3backend-pdf.dtx
> +   \int_compare:nNnT{\mag} = {\@m}
Not keen on `\@m` in `expl3` code, nor `\mag` if we mean `\tex_mag:D`.

2022-06-21 22:12 UTC, davidcarlisle reviewed
The  danger of enabling this by default rather than say just for new documents specifying `\DocumentMetadata` is changes to existing layout

If this document is processed on a site which defaults pdf size to A4, you get an arrow pointing to 1, but setting the pge size here is like uncommenting graphics and the page number is cut off as the short page is enforced

```
\documentclass{article}
\addtolength\textheight{9\baselineskip}

%\usepackage{graphics}

\begin{document}

aa\\bb

\rule{20pt}{620pt}

page number here ...........................$\downarrow$

\end{document}
```

the existing document is "wong" as it is setting a letter paper page block on a A4 page, but the manual setting of `\textheight` is correcting for that so auomatically forcing the "correct" US Letter media size ends up losing the page foot. 

there are probably a lot of documents doing essentially this.

That said, if we could document this and make the change it would be a good thing, having a default of setting a US Letter text block on an A4 page is hard to justify.

2022-06-22 03:23 UTC, car222222 commented
Just a brief comment for now:

More generally, the whole of the backend, together with its related files such as l3pdf etc., will need a major cleanup/reworking before moving anything out of the experimental 'pdf-management/latex-lab' world.

2022-06-22 08:30 UTC, davidcarlisle commented
> I'm really not sure the \mag or 0pt tests are needed 

This was a historic compromise at the time to avoid breaking existing platex setup and in paticular avoiding timing issues over package loading order. With expl3 being in the format and so simplifying possible load orders, we can probably look at that again, with the platex maintainers.

> I think we don't need a second hook use.

Origially some dvi drivers had a "first page setting wins" and some had  "last page setting wins" and some had "last page setting wins, but must be on first page". That meant finding a place to insert the code was interesting.  But dvips changed its default and other dvi drivers have dropped out of use and I believe all supported back ends work in essentially the same way now with regard to timing, and as you say just spilt on needing a `\special` or setting internal registers

2022-06-22 12:59 UTC, josephwright commented
I'm working on ideas in https://github.com/latex3/latex3/compare/setpdfpagesize-alt?expand=1: backend part is done, but I want a common interface in `l3pdf` (to follow later).

2022-09-28 07:15 UTC, josephwright commented
Handled in a slightly different way after discussion.

2022-09-28 07:15 UTC, closed without merging