Deprecated \tl_sort:nN for \tl_sort_use:nN
latex3/latex3 pull request #1215
Opened 2023-05-19 15:29 UTC by josephwright

See #914

2023-05-19 17:56 UTC, FrankMittelbach approved these changes

2023-05-22 12:21 UTC, mrpiggi commented on l3kernel/doc/l3obsolete.txt
> +\tl_sort:nN                              2023-05-19
`\tl_reverse:n` is missing

2023-05-22 13:47 UTC, muzimuzhi reviewed
minor styling things

2023-05-22 13:47 UTC, muzimuzhi commented on l3kernel/CHANGELOG.md
> +-  `\tl_sort_use:nN` (was `\tl_sort:nN`)
extra space character between `-` and `` ` ``
```suggestion
- `\tl_reverse_use:n` (was `\tl_reverse:n`)
- `\tl_sort_use:nN` (was `\tl_sort:nN`)
```

2023-05-22 13:49 UTC, josephwright commented on l3kernel/testfiles/m3sort002.lvt
Done

2023-06-03 09:58 UTC, josephwright commented
Comments from anyone other than @FrankMittelbach?

2023-06-03 21:08 UTC, blefloch commented
We should consider the cases of `\tl_reverse_items:n` and `\tl_rescan:nn`.

2023-06-07 05:44 UTC, josephwright commented
I've looked at `\tl_reverse_items:n` and `\tl_rescan:nn` and 'm not sure they need a change. For both `\tl_reverse:n` and `\tl_sort:nn` the issue was that there is an `:N` version that's not expandable and not equal to the `V`-type variant. However, we have neither `\tl_rescan:Nn` nor `\tl_reverse_items:N`. So I'm not seeing a need to alter them.

2023-10-18 07:53 UTC, josephwright commented
Are we happy with this change? I've rebased, etc., so we are clean to merge.

2023-10-20 19:03 UTC, muzimuzhi requested changes
Another rebasing is required.

PS: `expl3-intro.tex` mentioned `\tl_reverse:n` twice,
```
./articles/expl3-intro.tex:219:With a macro like |\tl_reverse:n|, we know simply from the macro name that
./articles/expl3-intro.tex:220:it takes a single argument; |\tl_reverse:n{abc}|, which
```
Although `expl3-intro.tex` was not maintained for a long time...

2023-10-21 09:03 UTC, josephwright commented
> Another rebasing is required.
> 
> PS: `expl3-intro.tex` mentioned `\tl_reverse:n` twice,
> 
> ```
> ./articles/expl3-intro.tex:219:With a macro like |\tl_reverse:n|, we know simply from the macro name that
> ./articles/expl3-intro.tex:220:it takes a single argument; |\tl_reverse:n{abc}|, which
> ```
> 
> Although `expl3-intro.tex` was not maintained for a long time...

This is the source for a published TUGBoat article: as such, we will never update it again.

2023-10-21 09:05 UTC, josephwright commented on l3kernel/CHANGELOG.md
> +-  `\tl_sort_use:nN` (was `\tl_sort:nN`)
Corrected

2023-10-21 09:06 UTC, josephwright commented on l3kernel/l3sort.dtx
>  % test.  If |#5| is the tail of the list, call \cs{tl_sort:nN} on |#1|
Corrected

2023-10-21 09:06 UTC, josephwright commented
@muzimuzhi Rebased again with those corrections

2023-10-21 10:00 UTC, muzimuzhi requested changes
Dates deprecated recorded in `l3obsolete.txt` should be updated to 2023-10-18, to be consistent with that in `l3deprecation.dtx` and `l3(tl|sort).dtx`.

2023-10-21 12:13 UTC, josephwright commented on l3kernel/doc/l3obsolete.txt
> +\tl_sort:nN                              2023-05-19
I'll update those if-and-when we actually merge

2023-10-22 21:21 UTC, blefloch commented
> I've looked at `\tl_reverse_items:n` and `\tl_rescan:nn` and 'm not sure they need a change. For both `\tl_reverse:n` and `\tl_sort:nn` the issue was that there is an `:N` version that's not expandable and not equal to the `V`-type variant. However, we have neither `\tl_rescan:Nn` nor `\tl_reverse_items:N`. So I'm not seeing a need to alter them.

Thinking about it some more (sorry for the delay), I realize there could be three versions of a given token list operation:
- take some `n`-type argument, apply the operation, and use the result;
- take some `n`-type argument, apply the operation, and store the result in a variable;
- take some variable, apply the operation, and store the result back into the variable.

| n to n | n to N | N to N |
|-------|--------|-----|
| `\tl_reverse:n` |  | `\tl_reverse:N` |
| `\tl_rescan:nn` | `\tl_set_rescan:Nnn` | |
| `\tl_sort:nn` | | `\tl_sort:Nn` |
| `\tl_trim_spaces:n` | | `\tl_trim_spaces:N` |

For all other pairs of functions where both `:n` and `:N` exists, the `:N` function is equivalent to expanding once before calling the `:n` function.  For instance `\tl_to_str:N`, `\tl_count:N`, `\tl_show:N`, `\tl_map_inline:Nn`, `\tl_head:N`… I suspect that it would make more sense to add the word `set` to `\tl_reverse:N`, `\tl_sort:Nn` and `\tl_trim_spaces:N`, or add the word `use` to `\tl_reverse:n`, `\tl_sort:nn`, `\tl_trim_spaces:n` (and maybe `\tl_rescan:nn` as well).

2023-10-23 07:49 UTC, FrankMittelbach reviewed
Seeing Bruno's comments I think that I should take my earlier approval back. If one looks at the larger picture then we don't use `_use` anywhere except when we "use some register", e.g., stuff like `\dim_use:N` (N in the signature). The only other  "use" is the use module where nothing is done to the arguments other then selecting some of the argument (and possibly prehandling via "c"  etc.

All the ":n" functions that do something to the argument and then pass it back to the input stream only have the action in their name and the "use" is implicit. Of course one could add  `_use` to all of them but the convention without it very common and I think easy to understand.

Given that and given that when something is stored we normally have `_set` in the name across all modules, I think that his suggestion to add `_set` to  `\tl_sort:Nn`, either as `\tl_set_sort: Nn` (or maybe as `\tl_set_sorted:Nn` but I guess I would stay with "sort") and also to the others that save their result back into a var.

2023-10-23 08:02 UTC, josephwright commented
> Given that and given that when something is stored we normally have `_set` in the name across all modules, I think that his suggestion to add `_set` to `\tl_sort:Nn`, either as `\tl_set_sort: Nn` (or maybe as `\tl_set_sorted:Nn` but I guess I would stay with "sort") and also to the others that save their result back into a var.

I remember suggesting `\tl_set_sorted:Nn` ages ago :)

More seriously, I think I'd prefer `\tl_set_sort:Nn` over `\tl_sort_use:n` - I'm going to close the PR as a result and will look at an alternative one.

2023-10-23 08:02 UTC, closed without merging

2023-10-23 08:19 UTC, FrankMittelbach commented
> I remember suggesting `\tl_set_sorted:Nn` ages ago :)

quite likely
> 
> More seriously, I think I'd prefer `\tl_set_sort:Nn` over `\tl_sort_use:n` - I'm going to close the PR as a result and will look at an alternative one.

Bruno's main point was the need to do that to a few other N commands as well and I don't think that was on the table before (and I think he is right there).