\if:w documentation
latex3/latex3 pull request #1440
Opened 2024-02-11 06:21 UTC by jlaurens

Problems solved:
- <token_1> and <token_2> notations used only once
- <true code> not well defined
- typo
- legal construct not covered:
```
\def\x{xYES\else: NO\fi:}
\def\y{yNO\else: YES\fi:}
\if:w x\x
\if:w x\y
```

2024-02-11 06:32 UTC, car222222 requested changes
Two extra adjustments noticed.

2024-02-11 06:32 UTC, car222222 commented on l3kernel/l3basics.dtx
>  %   unexpandable tokens \meta{token_1} and \meta{tokens_2} are left;
Should be:   token_2

Better:
. . . are found;

2024-02-11 06:32 UTC, car222222 commented on l3kernel/l3basics.dtx
> +%   With "\exp_not:N", you can prevent the expansion of a token. "\if_catcode:w"
Maybe better with a new paragraph after:  . . . token.

2024-02-11 06:42 UTC, muzimuzhi commented
Personally, since `\if:w`, `\if_charcode:w`, and `\if_catcode:w` are aliases of primitives, I think their detailed documentation can be omitted from `interface3.pdf`.

2024-02-11 12:15 UTC, jlaurens commented
I initially asked for a change in the documentation because it was not consistent with the description of the texbook. So removing the doc is an option
Cons:
- the file is less self contained
- we must have access to offline reliable original documentation to compensate
Pros
- the TeXbook.pdf is available online (there might be legal restrictions)
- TeX by topic is in TeXLive
- There are other expl APIs for the same purpose
- documenting only expl APIs promotes their usage
- send the message 'you can avoid complicated TeX primitives'

2024-02-11 18:37 UTC, Skillmon commented
>     * the TeXbook.pdf is available online (there might be legal restrictions)

There are, none of the PDFs you find on the internet are likely to be legally distributed, you might want to report those sources if you find them.

That said, the TeXbook sources are on CTAN and free and you might read them (but you're not allowed to build a PDF from them).

2024-02-11 20:14 UTC, josephwright commented
> Personally, since `\if:w`, `\if_charcode:w`, and `\if_catcode:w` are aliases of primitives, I think their detailed documentation can be omitted from `interface3.pdf`.

No - as they are given documented `expl3` names. Anything documented as part of the `expl3` API need documentation which covers the uses they can be put to. That doesn't necessarily mean all of the coverage as-in The TeXbook. For example, `\exp_not:n` is `\unexpanded` renamed, but it is documented as taking an `n`-type argument: that means that using say `\exp_not:n \exp_after:wN { ... }` is not supported (and indeed the reason we have `\__kernel_exp_not:w`).

So _appropriate_tightening of the docs is fine.

2024-02-11 20:17 UTC, josephwright commented
@jlaurens I'm confused here: you've asked to undone the tightening up I made at your request? For example,`\if:w` needs only to be followed by one token - what's important for the test is what it expands to. So `<token_1> <token_2>` is misleading.

2024-02-15 12:14 UTC, jlaurens commented
Changes: 
- left→found
- \if_charcode:w == \if:w put first to explain why there is no example of  \if_charcode:w usage
- \else: optional when in front of \fi:
- nesting is allowed
- <token_1> and <token_2> used twice

2024-02-15 12:50 UTC, merged