Support Oklab and Oklch as interface color models
latex3/latex3 pull request #1500
Opened 2024-03-05 10:54 UTC by mgkurtz

As wished in https://github.com/latex3/xcolor/issues/26, I wrote a function converting from some LCh color space (name Oklch based on [Oklab](https://bottosson.github.io/posts/oklab)) to the standard RGB color space. That seemed easier to do with l3color, so I did it here.

IMHO it would make much sense to allow mixing colors in Oklab, and thus provide it as a core color model. Though, that seems better suited in a package like xcolor outside the kernel. So, likely I will also port the code to xcolor after all.

2024-03-28 14:45 UTC, josephwright commented
Can I ask where this comes up: I'm no expert but have never seen it 'in the wild' (Cf. L*a*b*)

2024-04-26 16:52 UTC, mgkurtz commented
Most prominently, Oklab is part of [CSS Color Module Level 4](https://www.w3.org/TR/css-color-4/#ok-lab). Since Oklab is relatively new, it did not go much into the wilds besides CSS. I just thought that when Oklab is qualitatively better than CIE Lab, then it makes more sense to support Oklab. Actually, I could easily add some more color models, it is just a matter of adapting this code and copy pasting some matrices mostly.

Anyway, rethinking this PR, I am more in favor of adding additional color models to xcolor only instead of bloating the kernel. Though, we may still discuss here, whether the concept of xcolor providing more color models than the kernel is wanted at all.

2024-04-27 07:34 UTC, josephwright commented
@mgkurtz  Longer-term plans are to move colour support into the kernel, so don't worry about 'bloat' here. The key question for me is whether we need this approach given that PDF doesn't support it.

2024-04-27 13:12 UTC, mgkurtz commented
Indeed, my point is that we do not necessarily need Oklab, CIE Lab or whatever in the kernel. Still some people would definitely like to use it. So, even if xcolor should mostly or totally merge with l3color, I see reason to have packages allowing more color models than those, which are generally needed and provided in the kernel.

Thus, what I believe, we need more than kernel support for Oklab is a simple officially documented macro like `\color_new_input_model:nnnN`, where `\color_new_input_model:nnnN { oklab } { 4 } { rgb } \mypackage_oklab:nnnn` creates code such as
```
\cs_new:Npn \__color_parse_model_oklch:w #1 , #2 , #3 , #4 \s__color_stop {
    { rgb } { \mypackage_oklab:nnnn {#1} {#2} {#3} {#4} }
}
```

Then, I can write `mypackage` with support for Oklab, CIE Lab, XYZ or who knows what and be happy.

2024-05-27 14:19 UTC, josephwright commented
I'm not keen on supporting generic model adding as it's _so_ rare: what I'd rather do is be sure that adding an extra model is a good idea. What I suppose that needs is some sense of likely take-up of such features.

2024-08-01 12:51 UTC, josephwright commented
I'm taking another look here. I can see the point about CCC4-like colours - but I can also see that we might want to know if they actually take off. @davidcarlisle you are the HTML expert - thoughts?

2024-08-03 09:46 UTC, car222222 commented
@josephwright wrote --

"I'm not keen on supporting generic model adding as it's so rare"

OK, but it would be good to at least provide some "hooks" (in the non-latex sense) to help people add such extra support via new packages.

In other words, set things up so that it is straightforward to provide an interface to any (reasonable) particular "colour space".

Note: it is a long time since I looked at the colour stuff so I am perhaps asking for something that would involve a complete rewrite! 

But we already provide a range of colour models of several distinct types, so I hope that providing a generic interface would not be so difficult.

2025-05-13 07:01 UTC, josephwright requested changes

2025-05-13 07:01 UTC, josephwright commented on l3kernel/l3color.dtx
> +      { \fp_eval:n { 1.055 * min ( 1 , #1 ) ^ (1/2.4) - 0.055 } }
Division is 'expensive' - can we pre-calculate `1/2.4`?

2025-05-13 07:01 UTC, josephwright commented on l3kernel/l3color.dtx
> +  }
Can we have the formulae for the expression in the source please?

2025-05-13 07:01 UTC, josephwright commented on l3kernel/l3color.dtx
> +  }
(As in in the comments part, typeset correctly)

2025-05-14 19:57 UTC, mgkurtz commented on l3kernel/l3color.dtx
> +      { \fp_eval:n { 1.055 * min ( 1 , #1 ) ^ (1/2.4) - 0.055 } }
The `\fp_eval:n` are in the T/F branches. I hope that `\fp_compare:nNnTF` keeps them as is.

2025-05-14 19:58 UTC, mgkurtz commented on l3kernel/l3color.dtx
> +      { \fp_eval:n { 1.055 * min ( 1 , #1 ) ^ (1/2.4) - 0.055 } }
I am going with 0.4166666666666667 now.

2025-05-14 20:05 UTC, mgkurtz commented
Thanks for coming back to this PR. I applied your changes now. Though, I did not take the time to actually look at the build. If there is anything awry, I will revisit this on the weekend.

2025-05-14 20:30 UTC, josephwright commented
There are a few minor things but I can fix post-merge once the stray `a` is removed :)

2025-05-18 15:03 UTC, mgkurtz commented
I fixed the stray `a`s, corrected the math presentation and rebased on `develop` now.

2025-05-18 20:47 UTC, merged

2025-05-21 05:34 UTC, mgkurtz commented
A caveat to note about my code: Colors out of the sRGB gamut just get clipped to sRGB. This leads to possibly big hue distortions. Adding proper gamut clipping would require about a dozen lines of code more, when I just naïvely bisect the chroma.

2025-05-21 06:55 UTC, josephwright commented
@mgkurtz  Feel free to make a PR for the docs - I think that could readily be merged.